workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      groups:
        - env
      ios_signing:
        certificates:
          - travelog_distribution
        provisioning_profiles:
          - travelog_profile

    scripts:
      - name: Create .env
        script: |
          cat > .env <<EOF
          OPENAI_API_KEY=$OPENAI_API_KEY
          PERPLEXITY_API_KEY=$PERPLEXITY_API_KEY
          AERODATABOX_API_KEY=$AERODATABOX_API_KEY
          AVIATION_STACK_API_KEY=$AVIATION_STACK_API_KEY
          Maps__API_KEY=$Maps__API_KEY
          GEMINI_API_KEY=$GEMINI_API_KEY
          EOF

      - name: Install dependencies
        script: |
          flutter pub get

      - name: Set up code signing
        script: |
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles --project ios/Runner.xcodeproj

      - name: Build iOS
        script: |
          flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
          ls -R build/ios/ipa

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: Q26WF62U4A
        issuer_id: 57fb8587-154a-4f47-8751-53922573c21f
        submit_to_testflight: true